#!/bin/bash -o xtrace

rm -rf target/work
rm -rf target/modules 
mkdir target/work
mkdir target/modules 

ROOT_DIR=$PWD

JAVA_FX_LIBS=javafx-sdk-15.0.1/lib/
JAVA_FX_MODS=javafx-jmods-15.0.1/

SHADE_TEST_JAR=target/shade-test.jar
SHADE=shade.test

# ---------------------------
# generate jackson-core module

echo "Starting jdeps"

jdeps  --module-path "$ROOT_DIR/$JAVA_FX_LIBS" --add-modules javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,java.logging --generate-module-info target/work $SHADE_TEST_JAR

# ---------------------------
# build  jackson-core module

JARPATH=$SHADE_TEST_JAR
MOD=$SHADE

# copy original jar into place
cp $ROOT_DIR/$JARPATH $ROOT_DIR/target/modules/$MOD.jar

echo "Starting jar unpack"

# extract original jar
rm -rf classes
mkdir classes
cd classes
jar xf $ROOT_DIR/$JARPATH

echo "Starting javac to compile module info"

# compile module-info.java (generated by gen.sh)
cd $ROOT_DIR/target/work/$MOD
javac -p $MOD,javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,java.logging --module-path $ROOT_DIR/$JAVA_FX_MODS -d $ROOT_DIR/classes module-info.java

echo "Starting jar pack"

# update output jar
jar uf $ROOT_DIR/target/modules/$MOD.jar -C $ROOT_DIR/classes module-info.class

cd $ROOT_DIR

rm -rf target/work classes 

echo "modular jars are in $PWD/module"

cd target/modules
rm -rf target/build

echo "starting jlink (skipped)"

# jlink --strip-native-commands --strip-debug --no-header-files --no-man-pages --compress=2 --module-path $JAVA_HOME/jmods/:/Users/wiverson/src/shade-test/javafx-jmods-15.0.1/:$PWD --add-modules shade.test,javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,java.logging --launcher runner=shade.test/com.doublerobot.HelloWorld --output ../TestApp/build

echo "starting jpackage"

cd ..

rm -rf final
mkdir final

# jpackage --name TestApp --dest final --runtime-image TestApp

jpackage --jlink-options "--strip-native-commands --strip-debug --no-header-files --no-man-pages --compress=2"  --name TestApp --module-path $JAVA_HOME/jmods/:/Users/wiverson/src/shade-test/javafx-jmods-15.0.1/:$PWD/modules/ --add-modules shade.test,javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,java.logging  -m shade.test/com.doublerobot.HelloWorld

echo "Ready."
